---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uysdeccs/public_html/
    # Clear existing files first
    - /bin/rm -rf $DEPLOYPATH/*
    # Then copy new files
    - /bin/cp -R dist/* $DEPLOYPATH
    # Set permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;